version: '3.8'

services:
  app:
    image: boilerplate
    container_name: boilerplate-app
    build: .
    env_file: .env
    environment:
      - PORT=80
      - DATABASE_URL=postgres://postgres:postgres@db:15432/boilerplate
    ports:
      - 3000:80
    depends_on:
      - db
    command: yarn start
    restart: on-failure

  db:
    image: postgres
    container_name: boilerplate-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate
    ports:
      - 15432:15432
    volumes:
      - db-data:/var/lib/postgresql/data
    command: -p 15432
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: boilerplate-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       - pgadmin-data:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data:
  pgadmin-data:
